services:
  mysql:
    image: 'mysql:8.0'
    container_name: crud_spring_mysql
    environment:
      MYSQL_DATABASE: courses
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    volumes:
      - mysql_data_vol:/var/lib/mysql
    restart: always

volumes:
  mysql_data_vol: {}
