services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: courses
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - spring-mysql

  backend:
    build: .
    image: spring-api
    restart: always
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./target:/app
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/courses
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_FLYWAY_ENABLED: true
    networks:
      - spring-mysql

volumes:
  db-volume: {}

networks:
  spring-mysql:
    driver: bridge
